/*-----------Types of COMMENTS actions--------*/

/*---SAVE----*/
export const COMMENT_SAVE_SUCCESS = "COMMENT_SAVE_SUCCESS";
export const COMMENT_SAVE_FAILED = "COMMENT_SAVE_FAILED";
export const COMMENT_IS_SAVING = "COMMENT_IS_SAVING";
/*---FETCH----*/
export const COMMENT_FETCH_SUCCESS = "COMMENT_FETCH_SUCCESS";
export const ONE_COMMENT_FETCH_SUCCESS = "One_COMMENT_FETCH_SUCCESS";
export const COMMENT_FETCH_FAILED = "COMMENT_FETCH_FAILED";
export const COMMENT_IS_FETCHING = "COMMENT_IS_FETCHING";
/*---UPDATE----*/
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESS";
export const COMMENT_UPDATE_FAILED = "COMMENT_UPDATE_FAILED";
export const COMMENT_IS_UPDATING = "COMMENT_IS_UPDATING";

/*---PATCH----*/
export const COMMENT_PATCH_SUCCESS = "COMMENT_PATCH_SUCCESS";
export const COMMENT_PATCH_FAILED = "COMMENT_PATCH_FAILED";
export const COMMENT_IS_PATCHING = "COMMENT_IS_PATCHING";


/*---DELETE----*/
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAILED = "COMMENT_DELETE_FAILED";
export const COMMENT_IS_DELETING = "COMMENT_IS_DELETING";