/*-----------Types of STUDENTs actions--------*/

/*---SAVE----*/
export const STUDENT_SAVE_SUCCESS = "STUDENT_SAVE_SUCCESS";
export const STUDENT_SAVE_FAILED = "STUDENT_SAVE_FAILED";
export const STUDENT_IS_SAVING = "STUDENT_IS_SAVING";

/*---FETCH----*/
export const STUDENT_FETCH_SUCCESS = "STUDENT_FETCH_SUCCESS";
export const STUDENT_FETCH_FAILED = "STUDENT_FETCH_FAILED";
export const STUDENT_IS_FETCHING = "STUDENT_IS_FETCHING";
export const ONE_STUDENT_FETCH_SUCCESS = "ONE_STUDENT_FETCH_SUCCESS";
export const VERIFY_STUDENT = "VERIFY_STUDENT";

/*---UPDATE----*/
export const STUDENT_UPDATE_SUCCESS = "STUDENT_UPDATE_SUCCESS";
export const STUDENT_UPDATE_FAILED = "STUDENT_UPDATE_FAILED";
export const STUDENT_IS_UPDATING = "STUDENT_IS_UPDATING";

/*---PATCH----*/
export const STUDENT_PATCH_SUCCESS = "STUDENT_PATCH_SUCCESS";
export const STUDENT_PATCH_FAILED = "STUDENT_PATCH_FAILED";
export const STUDENT_IS_PATCHING = "STUDENT_IS_PATCHING";

/*---DELETE----*/
export const STUDENT_DELETE_SUCCESS = "STUDENT_DELETE_SUCCESS";
export const STUDENT_DELETE_FAILED = "STUDENT_DELETE_FAILED";
export const STUDENT_IS_DELETING = "STUDENT_IS_DELETING";

/*---SEARCH----*/
export const STUDENT_SEARCH = "STUDENT_SEARCH";

/*---PDF STUDENTS----*/
export const STUDENT_PDF = "STUDENT_PDF";
